---
abstract: 'Reading XML and providing path information based on a pull-parser. '
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Reader
requires:
  Acme::HTTP: '0'
  Carp: '0'
  Exporter: '0'
  XML::Parsepp: '0'
  XML::Parser: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/klaus03/XML-Reader
  repository: https://github.com/klaus03/XML-Reader.git
version: '0.65'
